### ISSUE TITLE
Want a help in my project.

### ISSUE THREAD

**Issue by anuragsri01** [atharva-18/Object-Detection-API#1]
i am trying to intregate my yolo model that detect wine bottles and their brands and want to call the model whenever any user uploads an image in it. i am not able to figure it out and got stuck here please help.

**Comment by atharva-18** [comment]
You must train YOLO to detect custom objects.
Have a look here - https://medium.com/@manivannan_data/how-to-train-yolov3-to-detect-custom-objects-ccbcafeb13d2
After training, place the `yolov3.cfg` and `classes.names` files in the `./cfg` directory.
