### ISSUE TITLE
can't show detected image

### ISSUE THREAD

**Issue by andhana** [atharva-18/Object-Detection-API#3]
hi @atharva-18, 
The code is works well, but can't show detected image result in browser.
How to save input and output image in spesific direcory?

**Comment by atharva-18** [comment]
You need a cloudinary account for image hosting.
After registering, go to your console. You'll find your cloud name, API key and API secret on the dashboard. Copy those to your `settings.py` file.
There is a field for cloudinary config in the `settings.py` file

**Comment by andhana** [comment]
what if without cloudinary, process the input and output image in local directory?

**Comment by atharva-18** [comment]
You need to change how the plot is saved under the `plot_boxes()` function in `detect_image/utils/utils.py`.
